# This is a basic workflow to help you get started with Actions

name: CI MRZ JS

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocJS ] && rm -rf DBRDocJS 
          [ -d mrz-scanner-docs-web-dev ] && rm -rf mrz-scanner-docs-web-dev
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
      # Runs a set of commands using the runners shell
      - name: Build the site - Main
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocJS
          git clone --depth 1 https://github.com/dynamsoft-docs/mrz-scanner-docs-web-dev.git mrz-scanner-docs-web-dev
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./mrz-scanner-docs-web-dev/* ./DBRDocJS/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DBRDocJS/
          cd DBRDocJS && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DBRDocJS/_site/
          server-dir: /www.dynamsoft.com/mrz-scanner/docs/web/        

      - name: Trigger Webhook 
        run: | 
          curl -X POST -H "${{ secrets.WEBHOOK_USER }}" -H "${{ secrets.WEBHOOK_TOKEN }}" -H "Content-Type: application/json" -d "[\"/barcode-reader/docs/web/*\"]" ${{ secrets.WEBHOOK_URL }}


  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocJS-preview ] && rm -rf DBRDocJS-preview 
          [ -d mrz-scanner-docs-web-dev-preview ] && rm -rf mrz-scanner-docs-web-dev-preview
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
      # Runs a set of commands using the runners shell
      - name: Build the site - Preview
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocJS-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/mrz-scanner-docs-web-dev.git mrz-scanner-docs-web-dev-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./barcode-reader-docs-js-preview/* ./DBRDocJS-preview/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DBRDocJS-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocJS-preview/_config.yml
          cd DBRDocJS-preview && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocJS-preview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/web/        